### DISCUSSION TITLE
How to access swagger UI?

### DISCUSSION THREAD

**Discussion by MrOwen** [the-booklore/booklore#470] [General]
Awesome project and I'm wanting to extend it using the api! I saw `/swagger-ui/**", "/v3/api-docs/**` are protected routes and I saw those are the default paths but when I go to these, I just get redirected to the login page. I'm not so up on my knowledge on how spring auth works for this stuff so would love if you had any general direction on how to access the api docs. Thank you!

**Comment by acx10** [comment]
You will need to set SWAGGER_ENABLED=true in your docker compose file first and then swagger UI will be available at http://localhost:8080/swagger-ui/index.html

```
services:
  booklore:
    image: ghcr.io/adityachandelgit/booklore-app:latest
    container_name: booklore
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - **SWAGGER_ENABLED=true** 
```
