### DISCUSSION TITLE
CasaOS support

### DISCUSSION THREAD

**Discussion by CaptechOmar** [the-booklore/booklore#500] [Q&A] [answered]
I tried running the docker compose file from the terminal and I tried copying the yml file to casaos through the install a customized app
And in both ways I ended up with a blank page
Can someone please make a guide for how to install this on casaos?
Or 
I can share the logs here if anyone can help me through those

**Comment by sandpaperback** [comment]
Casa doesn't let you create multi container setups directly, which is weird because the folks that create packages can. I havent spent time trying to figure it out. Instead, I just created the compose file in a subdirectory in home and run it that way.

**Comment by sandpaperback** [comment, marked as answer]
My steps:

1. In CasaOS file browser, create a booklore folder inside AppData.
2. In your new /DATA/AppData/booklore folder, create data and mariadb folders. And in mariadb, make a config folder.
3. Still in file browser, click Root, then go to the home directory. Click to open the folder with your name. Create directory for booklore.
4. On your PC, take the sample compose file and update (working top to bottom):
- DATABASE_PASSWORD=_whateveryouchoose_
- under volumes, /DATA/AppData/booklore/data:/app/data and /pathtoyourbooks:/books
- MYSQL_ROOT_PASSWORD=_differentthanthefirstone_
- MYSQL_PASSWORD=**same as DATABASE_PASSWORD above**
- under vovolumes, /DATA/AppData/booklore/mariadb/config:/config

5. Save your compose.yaml
6. Return to your /home/you/booklore directory and upload your compose file.
7. Open the CasaOS terminal and log in.
8. `cd booklore`
9. `sudo docker compose up -d`
10. Enter your Casa user password and wait.

All done!

**Reply by MBaliver** [reply]
Would you mind sharing your final .yaml? I've been fiddling with mine for the last two hours without any success.

**Reply by CaptechOmar** [reply]
I'm eternally glad for you answer
It worked.
However, As soon as I tried to set the port from casaos interface -so I can implement it as a casaos app- I got to plan page again.
I don't know why

**Reply by sandpaperback** [reply]
@MBaliver  Sure.

```
services:
  booklore:
    image: ghcr.io/adityachandelgit/booklore-app:latest
    container_name: booklore
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - DATABASE_URL=jdbc:mariadb://mariadb:3306/booklore # Only modify this if you're familiar with JDBC and your database setup
      - DATABASE_USERNAME=booklore # Must match MYSQL_USER defined in the mariadb container
      - DATABASE_PASSWORD=password1goeshere # Use a strong password; must match MYSQL_PASSWORD defined in the mariadb container 
      - SWAGGER_ENABLED=false # Enable or disable Swagger UI (API docs). Set to 'true' to allow access; 'false' to block access (recommended for production).
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "6060:6060"
    volumes:
      - /DATA/AppData/booklore/data:/app/data
      - /mnt/media/books:/books
    restart: unless-stopped

  mariadb:
    image: lscr.io/linuxserver/mariadb:11.4.5
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MYSQL_ROOT_PASSWORD=password2goeshere # Use a strong password for the database's root user, should be different from MYSQL_PASSWORD
      - MYSQL_DATABASE=booklore
      - MYSQL_USER=booklore # Must match DATABASE_USERNAME defined in the booklore container
      - MYSQL_PASSWORD=password1goeshere.again # Use a strong password; must match DATABASE_PASSWORD defined in the booklore container
    volumes:
      - /DATA/AppData/booklore/mariadb/config:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
```
